name: reviewdog
on: 
  push:
jobs:
  misspell:
    name: suggester / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1
      - name: suggester
        uses: reviewdog/action-suggester@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
